services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.example
    command: /bin/sh -c "npm run build && npm start"
    volumes:
      - .:/app
